### ISSUE TITLE
Basic user creation

### ISSUE THREAD

**Issue by nataajj** [Anonymous-Voting-App/Anonymous-Voting-App#18]
Ability to create account
Ability to login/logout
Linking a created poll to account logged in

**Comment by Jontzii** [comment]
Some notes related to this:

- Use bcrypt to hash the password on the backend
  - https://www.npmjs.com/package/bcrypt
- We should decide between using the Bearer scheme and cookies
  - Cookies
    - Set JWT to **http-only** cookies with like 1-hour expiration
    - Set JWT on every request -> middleware is good for this
    - Frontend automatically sends cookies
    - Backend middleware checks request cookies
  - Bearer
    - During authentication return the generated JWT token to frontend
    - Frontend saves the token to local storage etc
    - With every request, the frontend sends the token in the Authorization header
    - Backend reads it from the header and acts accordingly
