### ISSUE TITLE
Integration between frontend and backend

### ISSUE THREAD

**Issue by vrindavj** [Anonymous-Voting-App/Anonymous-Voting-App#74]
Set up integration between frontend and backend

**Comment by Jontzii** [comment]
API docs for this can be found from [https://d2l9c7s1roosdj.cloudfront.net/api/](https://d2l9c7s1roosdj.cloudfront.net/api/)

One thing to note when implementing this: do **not** hardcode the backend address, use the frontend origin (`window.location.origin`) and add `/api/`to that :)
